### ISSUE TITLE
[04:01:32] [Server thread/ERROR]: Error occurred while enabling RTUBiomeLib v1.8.1 (Is it up to date?)

### ISSUE THREAD

**Issue by NekomaDev** [IPECTER/RTUBiomeLib#38]
`java.lang.ExceptionInInitializerError: null
    at com.github.ipecter.rtu.biomelib.RTUBiomeLib.loadNMS(RTUBiomeLib.java:40) ~[RTUBiomeLib-1.8.1.jar:?]
    at com.github.ipecter.rtu.biomelib.RTUBiomeLib.onEnable(RTUBiomeLib.java:24) ~[RTUBiomeLib-1.8.1.jar:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
    at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[purpur-1.20.2.jar:git-Purpur-2095]
    at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.2.jar:git-Purpur-2095]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:660) ~[purpur-1.20.2.jar:git-Purpur-2095]
    at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:571) ~[purpur-1.20.2.jar:git-Purpur-2095]
    at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:632) ~[purpur-1.20.2.jar:git-Purpur-2095]
    at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:429) ~[purpur-1.20.2.jar:git-Purpur-2095]
    at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:345) ~[purpur-1.20.2.jar:git-Purpur-2095]
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1102) ~[purpur-1.20.2.jar:git-Purpur-2095]
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.20.2.jar:git-Purpur-2095]
    at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NumberFormatException: For input string: "git00"
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
    at java.lang.Integer.parseInt(Integer.java:662) ~[?:?]
    at java.lang.Integer.parseInt(Integer.java:778) ~[?:?]
    at com.github.ipecter.rtu.biomelib.VersionUtil$Version.<init>(VersionUtil.java:30) ~[RTUBiomeLib-1.8.1.jar:?]
    at com.github.ipecter.rtu.biomelib.VersionUtil.<clinit>(VersionUtil.java:11) ~[RTUBiomeLib-1.8.1.jar:?]
    ... 14 more`
    
    What could be the error and how to fix it? :<

**Comment by IPECTER** [comment]
use 1.9.0

**Comment by NekomaDev** [comment]
Thanks <3
